# Building

CFLAGS_COMMON	= -Wall

CFLAGS_DEBUG	= $(CFLAGS_COMMON) -g

CFLAGS_CPP_OPT	= -DNDEBUG
CFLAGS_OPT	= $(CFLAGS_COMMON) -O3

CFLAGS_PROFILE	= $(CFLAGS_OPT) -pg

CFLAGS_CPP	= $(CFLAGS_CPP_DEBUG)
CFLAGS		= $(CFLAGS_DEBUG)

# Installing

INSTALL_ROOT	= /usr/local
